name: dunno
description: "A gift suggestion app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  algoliasearch: ^1.38.0
  cached_network_image: ^3.4.1
  http: ^1.5.0
  intl_phone_field: ^3.2.0
  pin_input_text_field: ^4.5.2
  font_awesome_flutter: ^10.10.0
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  firebase_crashlytics: ^5.0.3
  cupertino_icons: ^1.0.8
  cloud_firestore: ^6.0.3
  equatable: ^2.0.7
  file_picker: ^10.3.3
  flutter_dotenv:  ^6.0.0
  firebase_analytics: ^12.0.3
  firebase_messaging: ^16.0.3
  firebase_remote_config: ^6.1.0
  firebase_storage: ^13.0.3
  flutter_slidable: ^4.0.3
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.4.1
  flutter_calendar_carousel: ^2.5.4
  flutter_svg: ^2.2.1
  flutter_typeahead: ^5.2.0
  get_it: ^8.2.0
  go_router: ^16.2.4
  intl: ^0.20.2
  lottie: ^3.1.0
  url_launcher: ^6.3.2
  share_plus: ^12.0.0
  smooth_page_indicator: ^1.2.1
  table_calendar: ^3.2.0
  in_app_review: ^2.0.11
  shared_preferences: ^2.5.3
  package_info_plus: ^9.0.0
  google_fonts: ^6.3.2
  syncfusion_flutter_sliders: ^31.1.23

  sp_firebase:
    path: ../spaza/spaza-packages/sp-firebase
  sp_user_repository:
    path: ../spaza/spaza-packages/user-repository
  sp_utilities:
    path: ../spaza/spaza-packages/sp-utilities

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/animations/
    - .env
