// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTYSAN0uoBEYGFy-3azfRrA0Lu8ZBSLKw',
    appId: '1:112952377151:android:a98def5ded2200ea6add8a',
    messagingSenderId: '112952377151',
    projectId: 'dunno-da82e',
    storageBucket: 'dunno-da82e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI81Hlt_8Qphmt82tmd6SHJQWwL-1-zQ8',
    appId: '1:112952377151:ios:744ce5c219e3a3146add8a',
    messagingSenderId: '112952377151',
    projectId: 'dunno-da82e',
    storageBucket: 'dunno-da82e.firebasestorage.app',
    iosBundleId: 'com.example.dunnoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiYb5hHVJ50JJ6Yk47vnxzsbz5uoV6JWg',
    appId: '1:112952377151:web:f33e72692f9fefb96add8a',
    messagingSenderId: '112952377151',
    projectId: 'dunno-da82e',
    authDomain: 'dunno-da82e.firebaseapp.com',
    storageBucket: 'dunno-da82e.firebasestorage.app',
    measurementId: 'G-17ZGTYJ9ZC',
  );
}
